In [1]:
import numpy as np

In [52]:
matrix = np.array([[178.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   8.,   6.,   0.],
        [  3., 182.,   0.,   0.,   0.,   0.,   0.,   0.,   7.,   0.,   0.],
        [  4.,   0., 185.,   0.,   0.,   0.,   0.,   0.,   3.,   0.,   0.],
[  3.,   0.,   0., 182.,   0.,   0.,   0.,   0.,   7.,   0.,   0.],
[  0.,   0.,   0.,   0., 184.,   0.,   0.,   0.,   8.,   0.,   0.],
[  1.,   0.,   0.,   0.,   0., 177.,   0.,   0.,   6.,   0.,   0.],
[  1.,   0.,   0.,   0.,   0.,  42., 147.,   0.,   2.,   0.,   0.],
[  4.,   0.,   0.,   0.,   0.,   0.,   0., 181.,   8.,   5.,   0.],
[  7.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 182.,   3.,   0.],
[  4.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   5., 183.,   0.],
[  9.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   4., 170.]])

In [53]:
print(matrix)

[[178.   0.   0.   0.   0.   0.   0.   0.   8.   6.   0.]
 [  3. 182.   0.   0.   0.   0.   0.   0.   7.   0.   0.]
 [  4.   0. 185.   0.   0.   0.   0.   0.   3.   0.   0.]
 [  3.   0.   0. 182.   0.   0.   0.   0.   7.   0.   0.]
 [  0.   0.   0.   0. 184.   0.   0.   0.   8.   0.   0.]
 [  1.   0.   0.   0.   0. 177.   0.   0.   6.   0.   0.]
 [  1.   0.   0.   0.   0.  42. 147.   0.   2.   0.   0.]
 [  4.   0.   0.   0.   0.   0.   0. 181.   8.   5.   0.]
 [  7.   0.   0.   0.   0.   0.   0.   0. 182.   3.   0.]
 [  4.   0.   0.   0.   0.   0.   0.   0.   5. 183.   0.]
 [  9.   0.   0.   0.   0.   0.   0.   0.   9.   4. 170.]]


In [54]:
total = matrix.sum(axis=1)

In [55]:
total_sum = total.sum()

In [56]:
print(total_sum)

2110.0


In [57]:
diagonal = np.diagonal(matrix)
correct = diagonal.sum()
print(correct)

1951.0


In [58]:
accuracy = (correct)/total_sum
print(accuracy*100)

92.46445497630333
