In [3]:
import os

import pandas as pd
import numpy as np
from numpy import loadtxt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC

import matplotlib.pyplot as plt

In [4]:
HOME_FOLDER = 'images/'
noOfFiles = 0
noOfDir = 0

In [5]:
for base, dirs, files in os.walk(HOME_FOLDER):
    print('Looking in : ',base)
    for directories in dirs:
        noOfDir += 1
    for Files in files:
        noOfFiles += 1

Looking in :  images/
Looking in :  images/0000000001
Looking in :  images/1000000000
Looking in :  images/0000000000
Looking in :  images/0000010000
Looking in :  images/0100000000
Looking in :  images/0000001000
Looking in :  images/0000100000
Looking in :  images/0001000000
Looking in :  images/0010000000
Looking in :  images/0000000100
Looking in :  images/0000000010


In [6]:
print('Number of files',noOfFiles)
print('Number of Directories',noOfDir)
print('Total:',(noOfDir + noOfFiles))

Number of files 10532
Number of Directories 11
Total: 10543


In [7]:
image_data = pd.read_csv('data.csv') 

In [8]:
for col in image_data.columns:
    print(col)

index
filepath
label
type


In [9]:
image_data.shape

(10520, 4)

In [10]:
image_data.head()

index                                           filepath     label   type
0    785  images/0010000000/image-2021-05-06_02-51-02_16...  10000000  train
1    726  images/0000000100/image-2021-05-06_11-58-58_16...       100  train
2    261  images/0000000001/image-2021-05-06_03-14-41_16...         1  train
3    620  images/0000000001/image-2021-05-06_11-53-37_16...         1  train
4    737  images/0000000000/image-2021-05-06_12-03-06_16...         0  train

In [11]:
image_data.head()

index                                           filepath     label   type
0    785  images/0010000000/image-2021-05-06_02-51-02_16...  10000000  train
1    726  images/0000000100/image-2021-05-06_11-58-58_16...       100  train
2    261  images/0000000001/image-2021-05-06_03-14-41_16...         1  train
3    620  images/0000000001/image-2021-05-06_11-53-37_16...         1  train
4    737  images/0000000000/image-2021-05-06_12-03-06_16...         0  train

In [12]:
image_data.head()

index                                           filepath     label   type
0    785  images/0010000000/image-2021-05-06_02-51-02_16...  10000000  train
1    726  images/0000000100/image-2021-05-06_11-58-58_16...       100  train
2    261  images/0000000001/image-2021-05-06_03-14-41_16...         1  train
3    620  images/0000000001/image-2021-05-06_11-53-37_16...         1  train
4    737  images/0000000000/image-2021-05-06_12-03-06_16...         0  train

In [13]:
labels = image_data["label"]

In [14]:
labels.head()

0    10000000
1         100
2           1
3           1
4           0
Name: label, dtype: int64

In [15]:
filepath = image_data["filepath"]

In [16]:
filepath.head()

0    images/0010000000/image-2021-05-06_02-51-02_16...
1    images/0000000100/image-2021-05-06_11-58-58_16...
2    images/0000000001/image-2021-05-06_03-14-41_16...
3    images/0000000001/image-2021-05-06_11-53-37_16...
4    images/0000000000/image-2021-05-06_12-03-06_16...
Name: filepath, dtype: object

LOADING THE DATA FROM CSV AND TEXT FILES

In [17]:
feature_matrix = loadtxt('feature_matrix.csv', delimiter=',')
print(feature_matrix)

[[0.30346028 0.15948293 0.         ... 0.12524595 0.25748246 0.29519896]
 [0.30946503 0.17313736 0.         ... 0.         0.0051749  0.02276182]
 [0.23542511 0.07095934 0.01789799 ... 0.08694436 0.01556499 0.33173583]
 ...
 [0.11950011 0.01052549 0.02519937 ... 0.04093295 0.09136424 0.27559997]
 [0.03613472 0.02182281 0.01063083 ... 0.01606922 0.03540979 0.33080187]
 [0.33017644 0.07390193 0.1140622  ... 0.00145886 0.00188124 0.        ]]


In [18]:
labels = np.loadtxt("labels.txt", dtype=str)
print(len(labels))
print(labels)

10520
['0000000001' '0000000001' '0000000001' ... '0000000010' '0000000010'
 '0000000010']


PCA: principal component analysis

In [19]:
ss = StandardScaler()
standardized_features = ss.fit_transform(feature_matrix)
pca = PCA(n_components=500)
pca = ss.fit_transform(standardized_features)
print('The shape of the PCA matrix is: ', pca.shape)

The shape of the PCA matrix is:  (10520, 3780)


In [20]:
X = pd.DataFrame(pca)
y = pd.Series(labels)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=.3,
                                                    random_state=1234123)

pd.Series(y_train).value_counts()

0001000000    699
0000100000    693
0000000010    693
0000000100    682
0000000001    676
0010000000    675
0000001000    655
0000010000    652
1000000000    650
0100000000    646
0000000000    643
dtype: int64

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

model = SVC()
model.fit(X_train, y_train)
  
predictions = model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

  0000000000       0.46      0.51      0.48       317
  0000000001       0.47      0.67      0.55       284
  0000000010       0.47      0.52      0.49       267
  0000000100       0.74      0.63      0.68       278
  0000001000       0.83      0.64      0.72       305
  0000010000       0.71      0.56      0.62       268
  0000100000       0.47      0.66      0.55       267
  0001000000       0.38      0.57      0.46       261
  0010000000       0.79      0.42      0.55       285
  0100000000       0.65      0.52      0.58       314
  1000000000       0.64      0.54      0.58       310

    accuracy                           0.56      3156
   macro avg       0.60      0.57      0.57      3156
weighted avg       0.60      0.56      0.57      3156



In [24]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['linear']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.803 total time=  40.9s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.806 total time=  38.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.821 total time=  37.5s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.798 total time=  41.2s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.813 total time=  38.3s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.803 total time=  39.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.806 total time=  38.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.821 total time=  36.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.798 total time=  42.4s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.813 total time=  36.5s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.803 total time=  36.8s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

TRAINING WITH THE RBF KERNEL

In [132]:
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)

SVC(probability=True, random_state=42)

In [136]:
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('The accuracy of the SVM model is: ', accuracy)

The accuracy of the SVM model is:  0.5649556400506971


TRAINING WITH THE LINEAR KERNEL

In [25]:
svm = SVC(kernel='linear', gamma = 0.0001, probability=True, random_state=42)
svm.fit(X_train, y_train)

SVC(gamma=0.0001, kernel='linear', probability=True, random_state=42)

In [26]:
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('The accuracy of the SVM model is: ', accuracy)

The accuracy of the SVM model is:  0.8222433460076045


TRAINING WITH THE POLY KERNEL

In [139]:
svm = SVC(kernel='poly', probability=True, random_state=42)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('The accuracy of the SVM model is: ', accuracy)

The accuracy of the SVM model is:  0.6486058301647655


TRAINING WITH THE SIGMOID KERNEL

In [140]:
svm = SVC(kernel='sigmoid', probability=True, random_state=42)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('The accuracy of the SVM model is: ', accuracy)

The accuracy of the SVM model is:  0.25190114068441066
